# Imagen base de Python
FROM python:3.11-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo Python al contenedor
COPY bank_oop.py .

# Comando para ejecutar el programa al iniciar el contenedor
CMD ["python", "bank_oop.py"]
