# Imagen base oficial de Python
FROM python:3.11-slim

# Carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo Python al contenedor
COPY ejercicioclasebanco.py .

# Comando que se ejecutará al iniciar el contenedor
CMD ["python", "ejercicioclasebanco.py"]
